# Generated by Django 4.2.6 on 2023-10-25 22:06

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100, verbose_name='Действие')),
                ('time', models.TimeField(blank=True, null=True, verbose_name='Время выполнения')),
                ('duration', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(120)], verbose_name='Время на выполнение в секундах')),
                ('frequency', models.CharField(blank=True, choices=[('DLY', 'Ежедневно'), ('2d', 'Раз в 2 дня'), ('3d', 'Раз в 3 дня'), ('4d', 'Раз в 4 дня'), ('5d', 'Раз в 5 дней'), ('6d', 'Раз в 6 дней'), ('WLY', 'Еженедельно')], null=True, verbose_name='Частота выполнения')),
                ('created_at', models.CharField(blank=True, choices=[('Monday', 'Понедельник'), ('Tuesday', 'Вторник'), ('Wednesday', 'Среда'), ('Thursday', 'Четверг'), ('Friday', 'Пятница'), ('Saturday', 'Суббота'), ('Sunday', 'Воскресенье')], null=True, verbose_name='День создания')),
                ('place', models.CharField(max_length=100, verbose_name='Место выполнения')),
                ('is_pleasant', models.BooleanField(default=False, verbose_name='Признак приятной привычки')),
                ('reward', models.CharField(blank=True, max_length=100, null=True, verbose_name='Вознаграждение за привычку')),
                ('is_public', models.BooleanField(default=False, verbose_name='Признак публичности')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Создатель привычки')),
                ('related_pleasant_habit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='habits_app.habit', verbose_name='Связанная приятная привычка')),
            ],
            options={
                'verbose_name': 'Привычку',
                'verbose_name_plural': 'Привычки',
                'ordering': ('action',),
            },
        ),
        migrations.AddConstraint(
            model_name='habit',
            constraint=models.CheckConstraint(check=models.Q(('is_pleasant', False), ('frequency', True)), name='only_useful_habit_frequency'),
        ),
        migrations.AddConstraint(
            model_name='habit',
            constraint=models.CheckConstraint(check=models.Q(('is_pleasant', False), ('created_at', True)), name='only_useful_habit_created_at'),
        ),
    ]
