# Generated by Django 4.2.6 on 2023-10-25 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='habit',
            name='only_useful_habit_frequency',
        ),
        migrations.RemoveConstraint(
            model_name='habit',
            name='only_useful_habit_created_at',
        ),
        migrations.AddConstraint(
            model_name='habit',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('frequency', True), ('is_pleasant', False)), models.Q(('frequency', False), ('is_pleasant', True)), _connector='OR'), name='only_useful_habit_frequency'),
        ),
        migrations.AddConstraint(
            model_name='habit',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('created_at', True), ('is_pleasant', False)), models.Q(('created_at', False), ('is_pleasant', True)), _connector='OR'), name='only_useful_habit_created_at'),
        ),
    ]
