# Generated by Django 4.2.6 on 2023-10-25 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits_app', '0003_remove_habit_only_useful_habit_created_at'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='habit',
            name='only_useful_habit_frequency',
        ),
    ]
