# Generated by Django 4.2.6 on 2023-10-25 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='nickname',
        ),
        migrations.AddField(
            model_name='user',
            name='chat_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='ID чата ТГ'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_update',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='ID последнего сообщения'),
        ),
        migrations.AddField(
            model_name='user',
            name='tg_name',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Telegram аккаунт'),
        ),
    ]
